name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest

      - name: Generate coverage report
        id: generate_coverage_report
        run: |
          uv run coverage run -m pytest
          
          echo '## Coverage'                      >> ${GITHUB_STEP_SUMMARY}
          echo '```'                              >> ${GITHUB_STEP_SUMMARY}
          uv run coverage report   >> ${GITHUB_STEP_SUMMARY}
          echo '```'                              >> ${GITHUB_STEP_SUMMARY}

          uv run coverage report
          